### ISSUE TITLE
Bravo plugin scraper misses some videos (digital series, exclusives)

### ISSUE THREAD

**Issue by chris-prince** [learningit/Kodi-plugins-source#3]
While using the Bravo TV plugin, I noticed it wasn't finding "Last Chance Kitchen" episodes, which are an online-only accompaniment to "Top Chef".  For fans of "Top Chef", those online episodes are pretty important, as they have an impact on the TV series.

Digging into the plugin source, I realized the problem is that Bravo tags some videos as "Exclusive" or "Digital Series".[1] (And this is true of most Bravo shows, not just "Top Chef").  These online-only videos were not being caught by the existing scraper.

Three sets of changes are required to start including these online-only videos:
   1. Update the regexp patterns to extract the additional hrefs, and
   1. Update the json parsing code to better handle missing fields (as some json attributes are omitted for the online-only videos), and
   1. Update the list of attempted video URLs (as the online-only videos are served from a slightly different source).

I have a change that fixes all of these, which I will be submitting as a pull request.

Footnotes:
[1] - While videos tagged "Exclusive" and "Digital Series" are worth including, others tagged "Preview" and "Highlight" are not. My updated regexp handles this correctly.

**Comment by zcmack** [comment]
tested this on windows (jarvis) and openelec (isengard) and am not getting full episodes back. just getting digital exclusives.

**Comment by learningit** [comment]
This is NOT the place to get the latest update. I haven't merged the changes (and won't for a couple of days). Look for an update to the Kodi.org official repo.  The updated addon will be available there first.

**Comment by zcmack** [comment]
official addon seems to be broken as well, i'm assuming bravo changed their site. i was going to open an issue and attempt to fix but wanted to get some feedback first..

**Comment by learningit** [comment]
Don't bother, this source is way out of date. The updated one will come out through the kodi.org repo.

**Comment by zcmack** [comment]
but a PR was merged only 6 days ago... anyway, saw your post on the forums so i'll wait. just wanted to understand how these plugins worked and see if i could contribute. thanks for the work you do.
