### ISSUE TITLE
crashing on iOS 9.x and 10.x with Krypton

### ISSUE THREAD

**Issue by radicaldelusion** [learningit/Kodi-plugins-source#7]
I've tried several devices, both 32 and 64 bit, with iOS 9.x.x and 10.x.x, both jailbroken and non-jailbroken, and both this add-on, as well and wcbs both crash kodi when selecting an episode from any show. They work perfectly fine with jarvis, however, i'm running into problems with other addons using jarvis. WCBS and WNBC work fine with krypton on OS X so I'm totally baffled.

**Comment by learningit** [comment]
No idea. Report this in the proper support thread on the kodi.org forum and include a log posted to pastebin or xbmclogs. Can't help without a log.
